# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo 'Building the application'
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployToDev
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'windows-latest'
    dependsOn: Build
    steps:
    - download: current
      artifact: drop
    - script: echo 'Deploying to Dev environment'
      displayName: 'Deploy to Dev'
      # Add deployment steps (e.g., deploy to Azure App Service or copy files to server)

- stage: DeployToProd
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'windows-latest'
    dependsOn: DeployToDev
    steps:
    - download: current
      artifact: drop
    - script: echo 'Deploying to Prod environment'
      displayName: 'Deploy to Prod'
      # Add deployment steps for production environment

